spring.cloud.config.uri: http://config-service:8888
eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
spring.rabbitmq.host: rabbitmq
token:
  expiration_time: 86400
  secret: abcdefg