spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/mydb
    username: root
    password: test1357


    git config --global user.email "thinkcsw@gmail.com"
  git config --global user.name "thinkcsw"