spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/mydb
    username: root
    password: test1357
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
gateway:
  ip: 172.19.0.11